[tool.poetry]
name = "bdd-formation-simplon"
version = "0.1.0"
description = ""
authors = ["Data_Avangers"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
scrapy = "^2.11.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
